# YAML has many versions, Therefore it is necessary to write which version
version: '3'

# here we have to define services
services:
  # here you define the service name
  frontend:
    # notice that the space define the followship
    # not we want to build image
    build: ./frontend
    ports:
      - '4000:3000'
    volumes:
    # this mean the folder node_modules will not be override by our folder
      # - /app/node_modules 
      - ./frontend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build: ./api
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app
